name: antarkanma
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  get_storage: ^2.1.1
  intl: ^0.19.0
  dio: ^5.7.0
  http_parser: any
  encrypt: any
  share_plus: any
  url_launcher: ^6.0.0
  carousel_slider: ^5.0.0
  photo_view: ^0.14.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  collection: ^1.15.0
  permission_handler: ^11.2.0
  crypto: ^3.0.6
  image_picker: ^1.0.7
  flutter_svg: ^2.0.7
  glassmorphism: ^3.0.0
  syncfusion_flutter_charts: ^28.1.36
  animations: ^2.0.8
  firebase_core: ^3.10.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/Logo_Antarkanma.svg

  fonts:
    - family: PalanquinDark
      fonts:
        - asset: assets/fonts/Palanquin_Dark/PalanquinDark-Regular.ttf
          weight: 400
        - asset: assets/fonts/Palanquin_Dark/PalanquinDark-Medium.ttf
          weight: 500
        - asset: assets/fonts/Palanquin_Dark/PalanquinDark-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Palanquin_Dark/PalanquinDark-Bold.ttf
          weight: 700
